[package]
name = "sharded-log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"
fs2 = "0.4.3"
fault-injection = "1.0.1"
